### ISSUE TITLE
Highlight scripts in multiline comments

### ISSUE THREAD

**Issue by pinpox** [ikatyang/tree-sitter-yaml#47]
Hey, is there a way to syntax-highlitht scripts in multi-line comments? E.g. I have yaml files like this:
```yaml
- foo:
  - bar: [ "baz" ]
- this:
  - |
    #!/bin/sh
    echo "test" $(var)
    cat /dev/null
```

And would ilke the string to be highlighted with bash highlighting.  I think this is referred to as injected or fenced languages in tree-sitter ([reference](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection))
