### ISSUE TITLE
Issue: highlighting breaks with long object lines

### ISSUE THREAD

**Issue by rejdeboer** [ikatyang/tree-sitter-yaml#59]
# What is the issue?

Whenever you have lines that contain a lot of logic, like if-statements and variables, the syntax highlighting below that logic line breaks. This problem is triggered when writing logic lines that are longer than 128 characters

# Steps to reproduce

## Working example
```yaml
example: 
 teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeest:
    test: test
    other_test: test

```

**nvim screenshot:**
![image](https://github.com/ikatyang/tree-sitter-yaml/assets/33692223/18e3d32b-ca4a-4770-b5ff-073e4d584f4e)

## Broken example (add one more e)
```yaml
example:
  teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeest:
    test: test
    other_test: test

```

**nvim screenshot:**
![image](https://github.com/ikatyang/tree-sitter-yaml/assets/33692223/323d8f49-b148-4e9c-bf2c-0640f2f571d8)

# What behavior is expected?

The syntax highlighting doesn't break when using lines that are longer than 128 characters

# What have I already tried?

- Update tree-sitter
- Disable synmaxcol limit: `:set synmaxcol 0`
- Run `:syntax sync fromstart`
